Fix setting up custom value for K8s_NAMESPACE
opendatahub-io/kubeflow pull request #20
Opened 2022-05-19 12:24 UTC by VaishnaviHire

This commit fixes setting up custom value for K8s_NAMESPACE when namespace is not already created.
The notebook-controller explicitly creates '*-system' namespace. The changes include removing any namespace created by
the controller and replacing namespace values for all resources

2022-05-19 14:52 UTC, VaishnaviHire commented
/cc samuelvl

2022-05-25 12:36 UTC, samuelvl requested changes

2022-05-25 12:44 UTC, VaishnaviHire commented on components/odh-notebook-controller/Makefile
> +	../notebook-controller/config/default/kustomization.yaml
Yes I will remove the one for ` /notebook-controller/config/overlays/openshift/namespace.yaml` , but we will need the one with `/notebook-controller/config/default/kustomization.yaml` to replace ns value [here](https://github.com/opendatahub-io/kubeflow/blob/master/components/notebook-controller/config/default/kustomization.yaml#L2)

2022-05-25 12:50 UTC, samuelvl commented on components/odh-notebook-controller/Makefile
> +	../notebook-controller/config/default/kustomization.yaml
The openshift overlay namespace replacement should take precedence over that one -> https://github.com/opendatahub-io/kubeflow/blob/master/components/notebook-controller/config/overlays/openshift/kustomization.yaml#L6

The existing sed changes this replacement:
```
sed -i'' -e 's@namespace: .*@namespace: '"${K8S_NAMESPACE}"'@' \
		../notebook-controller/config/overlays/openshift/kustomization
```

2022-05-25 13:07 UTC, samuelvl commented
/lgtm

2022-05-25 13:11 UTC, merged