WIP: bump controller-runtime version in odh-notebook-controller
opendatahub-io/kubeflow pull request #241
Opened 2024-01-17 08:51 UTC by rkpattnaik780

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-01-17 11:43 UTC, rkpattnaik780 commented
/test odh-notebook-controller-pr-image-mirror

2024-01-17 11:50 UTC, rkpattnaik780 commented
/test kf-notebook-controller-pr-image-mirror

2024-01-17 12:17 UTC, rkpattnaik780 commented
/test kf-notebook-controller-pr-image-mirror

2024-01-18 11:01 UTC, rkpattnaik780 commented
/test odh-notebook-controller-unit

2024-01-18 11:12 UTC, rkpattnaik780 commented
/test odh-notebook-controller-unit

2024-01-18 19:41 UTC, rkpattnaik780 commented on components/notebook-controller/go.sum
> -github.com/elazarl/goproxy v0.0.0-20180725130230-947c36da3153/go.mod h1:/Zj4wYkgs4iZTTu3o/KG3Itv/qCCa8VVMlb3i9OVuzc=
The [CVE-2023-37788](https://www.cve.org/CVERecord?id=CVE-2023-37788) was introduced through this dependency.

2024-01-30 06:27 UTC, harshad16 reviewed
Applying the changes to the cluster break the notebook-controller.
```
E0130 06:25:12.641300 1 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x179ac80), concrete:(*runtime._type)(0x17f2880), asserted:(*runtime._type)(0x17f12c0), missingMethod:""} (interface conversion: client.Object is *v1.Pod, not *v1.Event)
goroutine 72 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x164b8c0?, 0xc000902750})
/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:49 +0x75
```

Need to go over the code a little bit closely, will provide second review sooner

2024-01-30 08:11 UTC, rkpattnaik780 commented
> Applying the changes to the cluster break the notebook-controller.
> 
> ```
> E0130 06:25:12.641300 1 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x179ac80), concrete:(*runtime._type)(0x17f2880), asserted:(*runtime._type)(0x17f12c0), missingMethod:""} (interface conversion: client.Object is *v1.Pod, not *v1.Event)
> goroutine 72 [running]:
> k8s.io/apimachinery/pkg/util/runtime.logPanic({0x164b8c0?, 0xc000902750})
> /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x99
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
> /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:49 +0x75
> ```
> 
> Need to go over the code a little bit closely, will provide second review sooner

Thanks for the review. This might have been caused by the following change:
`https://github.com/opendatahub-io/kubeflow/pull/241/files#diff-a436986c5e93996f9035eee6798d064ab8659957e8443eb44b3a4d3db289bde4R741`

Have updated the PR.

2024-02-02 20:14 UTC, harshad16 requested changes
lgtm, tested it works well
just one more question:

2024-02-02 20:14 UTC, harshad16 commented on components/notebook-controller/Makefile
> +	GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20230216140739-c98506dc3b8e
Are these changes needed ? why is it needed

2024-02-02 21:00 UTC, harshad16 commented on components/notebook-controller/Makefile
> +	GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20230216140739-c98506dc3b8e
Never seems like i found the answer:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_kubeflow/247/pull-ci-opendatahub-io-kubeflow-v1.7-branch-kf-notebook-controller-unit/1753521090027589632
the ci fails to locate the resultant controller-gen.

ack, this fix the ci test.

2024-02-02 21:00 UTC, harshad16 approved these changes
/lgtm
/approve

Tested in a setup cluster, it seems to be running as required.

2024-02-02 21:03 UTC, merged

2024-02-02 22:07 UTC, harshad16 commented
/cherrypick stable