fix: update logic to add notebook label on create and restart
opendatahub-io/kubeflow pull request #292
Opened 2024-03-27 11:06 UTC by rkpattnaik780

## Description
The PR is a follow up to #265 .
New notebooks and restarted notebooks should contain the label `opendatahub.io/workbenches`

## How Has This Been Tested?
After updating image of `notebook-controller-deployment` to the built image:
1. Existing notebook pods shouldn't have the label `opendatahub.io/workbenches`.
2. Creating new notebooks should have the label `opendatahub.io/workbenches`.
3. Restarting old notebooks should add the mentioned label.

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2024-03-27 15:59 UTC, atheo89 commented
Tested on my end and it works as expected.
/lgtm

2024-03-28 04:04 UTC, harshad16 reviewed
left one comment ?

2024-03-28 13:59 UTC, harshad16 requested changes
Left a comment

2024-03-28 13:59 UTC, harshad16 commented on components/common/reconcilehelper/util.go
> +	}
Can we move this inside the line 129 
to be safe for restart-only.

2024-03-28 20:43 UTC, harshad16 approved these changes
/lgtm
/approve

thanks for work :100:

2024-03-28 20:47 UTC, merged

2024-04-04 13:29 UTC, harshad16 commented
/cherrypick stable